[package]
name = "vm"
version = "0.1.0"
edition = "2021"
authors = ["Ali Rahhal <arahhal997@gmail.com>", "Mohammad Rahhal <m.r992@gmail.com>"]

[dependencies]
byteorder = "1.4.3"
num_enum = "0.5.7"
common = { path = "../common" }