[package]
name = "runner"
version = "0.1.0"
edition = "2021"
authors = ["Ali Rahhal <arahhal997@gmail.com>", "Mohammad Rahhal <m.r992@gmail.com>"]

[dependencies]
common = { path = "../common" }
compiler = { path = "../compiler" }
vm = { path = "../vm" }
